chain: hardhat
contracts:
  - address: "0x5FbDB2315678afecb367f032d93F642f64180aa3"
    abi: charts/contract-event-processor/abi/DIMORegistry.json
  - address: "0xc6e7DF5E7b4f2A278906862b61205850344D4e7d"
    abi: charts/contract-event-processor/abi/VehicleId.json
  - address: "0x0000000071727De22E5E9d8BAf0edAc6f37da032"
    abi: charts/contract-event-processor/abi/zerodevEntrypoint.json
