contracts:
  - address: 0x90C4D6113Ec88dd4BDf12f26DB2b3998fd13A144
    chain: polygon
    abi: abi/VehicleId.json
  - address: 0xE261D618a959aFfFd53168Cd07D12E37B26761db
    chain: polygon
    abi: abi/tokenPolygon.json
  - address: 0x5fab9761d60419c9eeebe3915a8fa1ed7e8d2e1b
    chain: ethereum
    abi: abi/tokenMainnet.json
  - address: 0x80Ee7ec4493A1d7975ab900F94dB25ba7C688201
    chain: mumbai
    abi: abi/tokenMumbai.json

chains:
  - chain: polygon
    rpc_url: wss://polygon-mainnet.g.alchemy.com/v2/
    startBlock:
    contracts:
      - address: 0x90C4D6113Ec88dd4BDf12f26DB2b3998fd13A144
        abi: abi/VehicleId.json
      - address: 0xE261D618a959aFfFd53168Cd07D12E37B26761db
        abi: abi/tokenPolygon.json
  - chain: ethereum
    rpc_url: wss://eth-mainnet.ws.alchemyapi.io/v2/
    startBlock:
    contracts:
      - address: 0x5fab9761d60419c9eeebe3915a8fa1ed7e8d2e1b
        abi: abi/tokenMainnet.json
  - chain: mumbai
    rpc_url: wss://polygon-mumbai.g.alchemy.com/v2/
    startBlock:
    contracts:
      - address: 0x80Ee7ec4493A1d7975ab900F94dB25ba7C688201
        abi: abi/tokenMumbai.json
