chain: hardhat
contracts:
  - address: '0x5FbDB2315678afecb367f032d93F642f64180aa3'
    abi: charts/contract-event-processor/abi/DIMORegistry.json
  - address: '0xc6e7DF5E7b4f2A278906862b61205850344D4e7d'
    abi: charts/contract-event-processor/abi/VehicleId.json
