contracts:
  - address: 0x90C4D6113Ec88dd4BDf12f26DB2b3998fd13A144
    abi: abi/VehicleId.json
  - address: 0xE261D618a959aFfFd53168Cd07D12E37B26761db
    chain: polygon
    abi: abi/tokenPolygon.json
  - address: 0x5fab9761d60419c9eeebe3915a8fa1ed7e8d2e1b
    chain: ethereum
    abi: abi/tokenMainnet.json
  - address: 0x80Ee7ec4493A1d7975ab900F94dB25ba7C688201
    chain: mumbai
    abi: abi/tokenMumbai.json
  - address: 0x8104e3Ad430EA6d354d013A6789fDFc71E671c43
    chain: polygon
    abi: abi/KernelECDSAValidator.json
  - address: 0xd990393c670dcce8b4d8f858fb98c9912dbfaa06
    chain: polygon
    abi: abi/KernelWebAuthnValidator.json
