ETHEREUM_RPC_URL: wss://polygon-mainnet.g.alchemy.com/v2/
EVENT_STREAM_TOPIC: topic.contract.event
PARTITIONS: 1
KAFKA_BROKER: localhost:9092
POSTGRES_USER: postgres
POSTGRES_PASSWORD: postgres
POSTGRES_DB: postgres
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
BLOCK_CONFIRMATIONS: 5
MONITORING_PORT: 8888
