ETHEREUM_RPC_URL: wss://polygon-mainnet.g.alchemy.com/v2/
CONTRACT_EVENT_TOPIC: topic.contract.event
PARTITIONS: 1
KAFKA_BROKER: localhost:9092
DB:
  USER: dimo
  PASSWORD: dimo
  NAME: contract_event_processor
  HOST: localhost
  PORT: 5432
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
BLOCK_CONFIRMATIONS: 5
MONITORING_PORT: 8888
