BLOCKCHAIN_RPC_URL: wss://polygon-mainnet.g.alchemy.com/v2/
CONTRACT_EVENT_TOPIC: topic.contract.event
PARTITIONS: 1
KAFKA_BROKER: localhost:9092
DB:
  USER: postgres
  PASSWORD: postgres
  NAME: postgres
  HOST: localhost
  PORT: 5432
  MAX_OPEN_CONNECTIONS: 5
  MAX_IDLE_CONNECTIONS: 5
BLOCK_CONFIRMATIONS: 5
MONITORING_PORT: 8888
ENVIRONMENT: dev
CHAINS: [polygon]
ALCHEMY_API_KEY: put-your-api-key-here
STARTING_BLOCK: 54534725
