replicaCount: 1
image:
  repository: dimozone/contract-event-processor
  pullPolicy: IfNotPresent
  tag: 0.2.14
cronJob:
  enabled: false
env:
  ENVIRONMENT: prod
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
  BLOCK_CONFIRMATIONS: 5
  DIMO_REGISTRY_ADDRESS: '0xFA8beC73cebB9D88FF88a2f75E7D7312f2Fd39EC'
  RELAY_ADDRESSES: 0xcce4ef41a67e28c3cf3dbc51a6cd3d004f53acbd,0xE92a1B8078EBc01412ba6Ef878425f35B32D6bBb
config:
  chain: polygon
  contracts:
    - address: '0xba5738a18d83d41847dffbdc6101d37c69c9b0cf'
      abi: abi/VehicleId.json
    - address: '0xfa8bec73cebb9d88ff88a2f75e7d7312f2fd39ec'
      abi: abi/DIMORegistry.json
    - address: '0x9c94c395cbcbde662235e0a9d3bb87ad708561ba'
      abi: abi/AftermarketDeviceId.json
    - address: '0xe9f4dfe02f895dc17e2e146e578873c9095ba293'
      abi: abi/DcnRegistry.json
    - address: '0x60627326f55054ea448e0a7bc750785bd65ef757'
      abi: abi/ResolverRegistry.json
    - address: '0x8129f3cd3eba82136caf5ab87e2321c958da5b63'
      abi: abi/Reward.json
    - address: '0x9A9D2E717bB005B240094ba761Ff074d392C7C85'
      abi: abi/DevLicenseDimo.json
    - address: '0x4804e8D1661cd1a1e5dDdE1ff458A7f878c0aC6D'
      abi: abi/SyntheticDeviceId.json
    - address: '0x3c152B5d96769661008Ff404224d6530FCAC766d'
      abi: abi/Sacd.json
    - address: '0xB4538A8D6AFab2849Ef78D08D49Dc1cc5AC2eD83'
      abi: abi/DIMOStaking.json
    - address: '0x41799E9Dc893722844E771a1C1cAf3BBc2876132'
      abi: abi/Connections.json
    - address: '0xf76eEBa34B19aDb7eEa9E4Eea05243D7E5a30123'
      abi: abi/StorageNode.json
    - address: '0xbfc07085736426295f60baa15dc70743e98fe612'
      abi: abi/Template.json
ingress:
  enabled: false
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-prod-dimo-kafka
