replicaCount: 1
image:
  repository: dimozone/contract-event-processor
  pullPolicy: IfNotPresent
  tag: 5a451c9
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
cronJob:
  enabled: false
  schedule: 0 0 * * 0
config:
  chain: goerli
  contracts:
    - address: '0x80ee7ec4493a1d7975ab900f94db25ba7c688201'
      abi: abi/Mumbai_OmidV2.json
env:
  ENVIRONMENT: dev
  MONITORING_PORT: 8888
  BLOCK_CONFIRMATIONS: 2
  KAFKA_BROKERS: kafka-dev-dimo-kafka-kafka-brokers:9092
  CONTRACT_EVENT_TOPIC: topic.contract.event
  DB_MAX_OPEN_CONNECTIONS: 10
  DB_MAX_IDLE_CONNECTIONS: 10
  DB_PORT: '5432'
  DB_NAME: contract_event_processor
  GAS_PRICE_FACTOR: 2
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dev.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '3'
    external-dns.alpha.kubernetes.io/hostname: contract-event-processor.dev.dimo.zone
  hosts:
    - host: contract-event-processor.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 250m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 192Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-dev-dimo-kafka
  topics: []
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
