replicaCount: 1
image:
  repository: dimozone/contract-event-processor
  pullPolicy: IfNotPresent
  tag: 0.2.14
cronJob:
  enabled: false
env:
  ENVIRONMENT: prod
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
  BLOCK_CONFIRMATIONS: 5
config:
  chain: ethereum
  contracts:
    - address: '0x5fab9761d60419c9eeebe3915a8fa1ed7e8d2e1b'
      abi: abi/Ethereum_Dimo.json
ingress:
  enabled: false
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-prod-dimo-kafka
  topics: []
