replicaCount: 1
image:
  repository: dimozone/contract-event-processor
  pullPolicy: IfNotPresent
  tag: '2984280'
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1001
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - all
cronJob:
  enabled: false
  schedule: 0 0 * * 0
config:
  chain: mumbai
  contracts:
    - address: '0x80ee7ec4493a1d7975ab900f94db25ba7c688201'
      abi: abi/Mumbai_OmidV2.json
    - address: '0x90c4d6113ec88dd4bdf12f26db2b3998fd13a144'
      abi: abi/VehicleId.json
    - address: '0x4de1bcf2b7e851e31216fc07989caa902a604784'
      abi: abi/DIMORegistry.json
    - address: '0xcf9af64522162da85164a714c23a7705e6e466b3'
      abi: abi/AftermarketDeviceId.json
    - address: '0x2daef6ff0e2b61aabf9adde1afdafdb4f0f1e660'
      abi: abi/DcnRegistry.json
    - address: '0x7ce3b10571b1ca517def45d5f81850467ec8dd2d'
      abi: abi/ResolverRegistry.json
    - address: '0x375885164266d48C48abbbb439Be98864Ae62bBE'
      abi: abi/Reward.json
    - address: '0x5dFe7f440ce475B90932b1eB4E70cc483f76Ae5c'
      abi: abi/DevLicenseDimo.json
env:
  ENVIRONMENT: dev
  MONITORING_PORT: 8888
  BLOCK_CONFIRMATIONS: 2
  KAFKA_BROKERS: kafka-dev-dimo-kafka-kafka-brokers:9092
  CONTRACT_EVENT_TOPIC: topic.contract.event
  DB_MAX_OPEN_CONNECTIONS: 10
  DB_MAX_IDLE_CONNECTIONS: 10
  DB_PORT: '5432'
  DB_NAME: contract_event_processor
  GAS_PRICE_FACTOR: 2
service:
  type: ClusterIP
  ports:
    mon-http:
      port: 8888
      targetPort: mon-http
      protocol: TCP
ports:
  - name: mon-http
    containerPort: 8888
    protocol: TCP
ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/auth-tls-secret: ingress/cf-origin-ca
    nginx.ingress.kubernetes.io/auth-tls-verify-client: 'on'
    nginx.ingress.kubernetes.io/enable-cors: 'true'
    nginx.ingress.kubernetes.io/cors-allow-origin: https://app.dev.dimo.zone
    nginx.ingress.kubernetes.io/limit-rps: '3'
    external-dns.alpha.kubernetes.io/hostname: contract-event-processor.dev.dimo.zone
  hosts:
    - host: contract-event-processor.dev.dimo.zone
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 250m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 192Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-dev-dimo-kafka
  topics:
    - name: topic.contract.event
      config:
        segment.ms: '3600000'
        compression.type: producer
        cleanup.policy: delete
        min.compaction.lag.ms: '3600000'
      partitions: 1
serviceMonitor:
  enabled: true
  path: /metrics
  port: mon-http
  interval: 30s
