replicaCount: 1
image:
  repository: dimozone/contract-event-processor
  pullPolicy: IfNotPresent
  tag: 0.1.3
cronJob:
  enabled: false
env:
  ENVIRONMENT: prod
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
  BLOCK_CONFIRMATIONS: 5
config:
  chain: polygon
  contracts:
    - address: '0xe261d618a959afffd53168cd07d12e37b26761db'
      abi: abi/Polygon_Dimo.json
    - address: '0xba5738a18d83d41847dffbdc6101d37c69c9b0cf'
      abi: abi/VehicleId.json
ingress:
  enabled: false
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
kafka:
  clusterName: kafka-prod-dimo-kafka
