replicaCount: 1
image:
  repository: dimozone/contract-event-processor
  pullPolicy: IfNotPresent
  tag: 0.1.1
cronJob:
  enabled: false
env:
  ENVIRONMENT: prod
  KAFKA_BROKERS: kafka-prod-dimo-kafka-kafka-brokers:9092
  BLOCK_CONFIRMATIONS: 5
ingress:
  enabled: false
resources:
  limits:
    cpu: 1
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 256Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 1
kafka:
  clusterName: kafka-prod-dimo-kafka
