apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "contract-event-processor.fullname" . }}-config-config-map
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "contract-event-processor.fullname" . | indent 4 }}
data:
  config.yaml: {{ .Values.config | toYaml | quote }}
