apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "contract-event-processor.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "contract-event-processor.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "contract-event-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/envconfigmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "contract-event-processor.selectorLabels" . | nindent 8 }}
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            {{- include "contract-event-processor.selectorLabels" . | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "contract-event-processor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: migrate
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command: ['sh', '-c', "/contract-event-processor migrate"]
          envFrom:
          - configMapRef:
              name: {{ include "contract-event-processor.fullname" . }}-config
          - secretRef:
              name: {{ include "contract-event-processor.fullname" . }}-secret
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ include "contract-event-processor.fullname" . }}-config
          - secretRef:
              name: {{ include "contract-event-processor.fullname" . }}-secret
          ports:
{{ toYaml .Values.ports | indent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: mon-http
          readinessProbe:
            httpGet:
              path: /
              port: mon-http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: abi
              mountPath: /abi
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
      volumes:
        - name: abi
          configMap:
            name: {{ include "contract-event-processor.fullname" . }}-abi-config-map
        - name: config
          configMap:
            name: {{ include "contract-event-processorfullname" . }}-config-config-map
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
