apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "contract-event-processor.fullname" . }}-alerts
  labels:
    {{- include "contract-event-processor.labels" . | nindent 4 }}
spec:
  groups:
  - name: contract-event-processor
    rules:
    - alert: AlchemyFailures
      expr: sum(rate(contract_event_processor_retry_count{namespace="{{ .Release.Namespace }}"}[2m])) > 0
      for: 2m
      labels:
        severity: critical
        namespace: {{ .Release.Namespace }}
      annotations:
        summary: "Failing to reach alchemy"
        description: Calls to alchemy have been failing for more than 2 minutes.'