apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "contract-event-processor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  backendType: secretsManager
  data:
    - key: {{ .Release.Namespace }}/contract_event/ethereum/rpc_url
      name: ETHEREUM_RPC_URL
    - key: {{ .Release.Namespace }}/contract_event/db/host
      name: DB_HOST
    - key: {{ .Release.Namespace }}/contract_event/db/user
      name: DB_USER
    - key: {{ .Release.Namespace }}/contract_event/db/pass
      name: DB_PASSWORD
