apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "contract-event-processor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/contract_event/ethereum/rpc_url
    secretKey: ETHEREUM_RPC_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/contract_event/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/contract_event/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/contract_event/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/contract_event/rpc_url/{{ .Values.config.chain }}
    secretKey: BLOCKCHAIN_RPC_URL
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "contract-event-processor.fullname" . }}-secret
    template:
      metadata: {}
